on:
  push:
    branches: main
name: 🚀 Deploy a FTP
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: buildear
        run: |
          npm install
          npm run build
